name: Electron Build for Mac

on:
  workflow_dispatch:
  push:
jobs:
  electron:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run --filter @xwiki/cristal-electron mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: electron_mac
          path: electron/dist/@xwikicristal-electron-*-arm64.dmg
